// <auto-generated />
using System;
using ArchT.Services.Search.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArchT.Services.Search.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SearchDb))]
    [Migration("20190425141742_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SearchDb")
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArchT.Services.Search.Contracts.OrderReportData", b =>
                {
                    b.Property<string>("OrderId");

                    b.Property<string>("ProductId");

                    b.Property<int>("Amount");

                    b.Property<string>("Name");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("OrderLines");

                    b.Property<string>("OrderStatus");

                    b.Property<decimal>("OrderTotal");

                    b.Property<decimal>("Price");

                    b.HasKey("OrderId", "ProductId");

                    b.ToTable("OrdersReport");
                });

            modelBuilder.Entity("ArchT.Services.Search.Contracts.ProductUpdated", b =>
                {
                    b.Property<string>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EventName");

                    b.Property<long>("EventSequence");

                    b.Property<DateTime>("EventTime");

                    b.Property<string>("Name");

                    b.Property<int>("Stock");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
