apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: archt-identity
    spec:
      containers:
        - image: archt/microservices.identity:latest
          imagePullPolicy: Always
          name: archt-identity
          env:
            - name: ConnectionStrings__IdentityDbConnection
              value: "Server=tcp:archt-db-server.database.windows.net,1433;Initial Catalog=archt-sqldb;Persist Security Info=False;User ID=archt-db-user;Password=archPASS123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service              
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: archt-identity